name: 'Build and release'

on:
  push:
    branches:
      - feat-ingress-unauth

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Pull the Docker Image builder
      run: docker pull homeassistant/amd64-builder
    - name: Build supervisor
      run: |
            docker run --rm --privileged \
              -v /var/run/docker.sock:/var/run/docker.sock \
              -v ~/.docker:/root/.docker \
              -v $PWD:/data \
              homeassistant/amd64-builder \
              --aarch64 \
              -t /data \
              --generic runner


